# Generated by Django 4.2 on 2023-06-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('periodo', models.IntegerField()),
                ('retorno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
