export const INVESTIMENTO_LIST_REQUEST = 'INVESTIMENTO_LIST_REQUEST'
export const INVESTIMENTO_LIST_SUCCESS = 'INVESTIMENTO_LIST_SUCCESS'
export const INVESTIMENTO_LIST_FAIL = 'INVESTIMENTO_LIST_FAIL'

export const INVESTIMENTO_REGISTER_REQUEST = 'INVESTIMENTO_REGISTER_REQUEST'
export const INVESTIMENTO_REGISTER_SUCCESS = 'INVESTIMENTO_REGISTER_SUCCESS'
export const INVESTIMENTO_REGISTER_FAIL = 'INVESTIMENTO_REGISTER_FAIL'

export const INVESTIMENTO_DELETE_REQUEST = 'INVESTIMENTO_DELETE_REQUEST'
export const INVESTIMENTO_DELETE_SUCCESS = 'INVESTIMENTO_DELETE_SUCCESS'
export const INVESTIMENTO_DELETE_FAIL = 'INVESTIMENTO_DELETE_FAIL'

export const INVESTIMENTO_UPDATE_REQUEST = 'INVESTIMENTO_UPDATE_REQUEST'
export const INVESTIMENTO_UPDATE_SUCCESS = 'INVESTIMENTO_UPDATE_SUCCESS'
export const INVESTIMENTO_UPDATE_FAIL = 'INVESTIMENTO_UPDATE_FAIL'