export const TAREFA_LIST_REQUEST = 'TAREFA_LIST_REQUEST'
export const TAREFA_LIST_SUCCESS = 'TAREFA_LIST_SUCCESS'
export const TAREFA_LIST_FAIL = 'TAREFA_LIST_FAIL'

export const TAREFA_REGISTER_REQUEST = 'TAREFA_REGISTER_REQUEST'
export const TAREFA_REGISTER_SUCCESS = 'TAREFA_REGISTER_SUCCESS'
export const TAREFA_REGISTER_FAIL = 'TAREFA_REGISTER_FAIL'

export const TAREFA_DELETE_REQUEST = 'TAREFA_DELETE_REQUEST'
export const TAREFA_DELETE_SUCCESS = 'TAREFA_DELETE_SUCCESS'
export const TAREFA_DELETE_FAIL = 'TAREFA_DELETE_FAIL'

export const TAREFA_UPDATE_REQUEST = 'TAREFA_UPDATE_REQUEST'
export const TAREFA_UPDATE_SUCCESS = 'TAREFA_UPDATE_SUCCESS'
export const TAREFA_UPDATE_FAIL = 'TAREFA_UPDATE_FAIL'