export const TAREFA_LIST_REQUEST = 'TAREFA_LIST_REQUEST'
export const TAREFA_LIST_SUCCESS = 'TAREFA_LIST_SUCCESS'
export const TAREFA_LIST_FAIL = 'TAREFA_LIST_FAIL'

export const TAREFA_REGISTER_REQUEST = 'TAREFA_REGISTER_REQUEST'
export const TAREFA_REGISTER_SUCCESS = 'TAREFA_REGISTER_SUCCESS'
export const TAREFA_REGISTER_FAIL = 'TAREFA_REGISTER_FAIL'