export const TAG_LIST_REQUEST = 'TAG_LIST_REQUEST'
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS'
export const TAG_LIST_FAIL = 'TAG_LIST_FAIL'

export const STATUS_LIST_REQUEST = 'STATUS_LIST_REQUEST'
export const STATUS_LIST_SUCCESS = 'STATUS_LIST_SUCCESS'
export const STATUS_LIST_FAIL = 'STATUS_LIST_FAIL'

export const CATEGORIA_LIST_REQUEST = 'CATEGORIA_LIST_REQUEST'
export const CATEGORIA_LIST_SUCCESS = 'CATEGORIA_LIST_SUCCESS'
export const CATEGORIA_LIST_FAIL = 'CATEGORIA_LIST_FAIL'